name: Postman (local)

on: [push, pull_request]

jobs:
  run-local-postman:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install backend deps
        run: pip install -r requirements.txt

      - name: Start Flask (background)
        env:
          PORT: 5000
        run: |
          python app.py &            # 背景啟動
          echo $! > flask.pid

      - name: Wait for server
        run: |
          for i in {1..30}; do
            curl -fsS http://127.0.0.1:5000/ && exit 0
            echo "waiting server..."; sleep 2
          done
          echo "server not up"; exit 1

      - name: Set up Node & Newman
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - run: npm install -g newman

      - name: Run Postman collection against localhost
        run: |
          # 依你變數名稱擇一覆蓋 base URL
          newman run tests/postman_collection.json \
            --env-var base_url=http://127.0.0.1:5000 || \
          newman run tests/postman_collection.json \
            --env-var baseURL=http://127.0.0.1:5000

      - name: Stop Flask
        if: always()
        run: kill $(cat flask.pid) || true
